jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Use JWT secret
      run: echo "The secret is available as an environment variable"
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET_KEY }}
